services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    env_file:  # This points to the .env file in your root directory
      - ./.env
    
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
