# Use a lightweight Node image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Install prerequisites
RUN apk add --no-cache curl bash

# Install dependencies
# COPY package*.json ./
RUN npm install express mysql2 @google-cloud/storage dotenv --save

# Cloud SQL Auth Proxy setup
ARG CLOUD_SQL_PROXY_VERSION=v2.0.0
RUN curl -o /usr/local/bin/cloud-sql-proxy \
    https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/${CLOUD_SQL_PROXY_VERSION}/cloud-sql-proxy.linux.amd64 \
    && chmod +x /usr/local/bin/cloud-sql-proxy

# Copy application code
COPY . .

# Expose the port the app runs on
EXPOSE 3000

# Make entrypoint script executable
RUN chmod +x /app/entrypoint.sh
ENTRYPOINT ["/app/entrypoint.sh"]

# Command to run the app
CMD ["node", "src/index.js"]