# Use a lightweight Node image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Install prerequisites
RUN apt update
RUN apt install -y curl
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
RUN nvm install stable
RUN nvm alias default stable

# Install dependencies
# COPY package*.json ./
RUN npm install express mysql2 @google-cloud/storage --save

# Cloud SQL Auth Proxy setup
ARG CLOUD_SQL_PROXY_VERSION=v2.0.0
RUN curl -o /usr/local/bin/cloud-sql-proxy \
    https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/${CLOUD_SQL_PROXY_VERSION}/cloud-sql-proxy.linux.amd64 \
    && chmod +x /usr/local/bin/cloud-sql-proxy

# Run the Cloud SQL Auth Proxy in the background
RUN /usr/local/bin/cloud-sql-proxy ${INSTANCE_CONNECTION_NAME} &

# Copy application code
COPY . .

# Expose the port the app runs on
EXPOSE 3000

# Command to run the app
CMD ["node", "src/index.js"]